[package]
name = "antlr"
version = "0.1.0"
authors = ["Josh Chase <josh@prevoty.com>"]
build = "build.rs"

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
lazy_static = "*"

[build-dependencies]
cmake = "*"
